### ISSUE TITLE
ProjectCracker fails to detect references

### ISSUE THREAD

**Issue by rojepp** [fsharp/FSharp.Compiler.Service#565]
Project Cracker Tool fails to detect references for the attached project. 
[ConsoleApplication3.zip](https://github.com/fsharp/FSharp.Compiler.Service/files/264555/ConsoleApplication3.zip)
#### Repro steps
1. Download the attached sample solution and open it in VS Code / Atom / other
#### Expected behavior

No errors
#### Actual behavior

Error squigglies on `open System.Data` in the editor. No type information for System.Data is available.

When running Project Cracker Tool, this error is shown:

> {ProjectFile =
> "C:\Users\robert\Documents\Visual Studio 2015\Projects\ConsoleApplication3\ConsoleApplication3\ConsoleApplication3.fsproj";
> Options = [||];
> ReferencedProjectOptions = [||];
> LogOutput =
> "Microsoft.Build.Exceptions.InvalidProjectFileException: The value "" of the "Project" attribute in element is invalid. Parameter "path" cannot have zero length.
> at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
> at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject(Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object arg0, Object arg1, Object arg2, Object arg3)
> ...
#### Related information

Originally reported here: https://github.com/fsharp/FsAutoComplete/issues/96
This machine has VS2015 installed, and has never had VS2013 installed. 
- Operating system : Win 10

**Comment by rojepp** [comment]
Unable to reproduce
