### ISSUE TITLE
FSharp.Compiler.Service coreclr package is broken

### ISSUE THREAD

**Issue by matthid** [fsharp/FSharp.Compiler.Service#591]
https://github.com/fsharp/FAKE/pull/1281

Please provide a succinct description of the issue. Opening a new fsi session fails:
```
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "FSIstrings.resources" was correctly embedded or linked into assembly "FSharp.Compiler.Service.netcore" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at FSIstrings.SR.GetStringFunc[T](String messageID, PrintfFormat`4 fmt)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$FSIstrings.fsiProductName@270.Invoke(Tuple`2 tupledArg)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.updateBannerText()
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible)
```

#### Repro steps

Steps are outlined in the first post of the linked issue.

#### Expected behavior

It should work.

#### Actual behavior

Exception (see above)

#### Known workarounds

None

#### Related information 

CoreCLR

It seems like the resources are not named correctly in the `FSharp.Compiler.Service.netcore` assembly:

![fsharp compiler service netcore_resourceerror](https://cloud.githubusercontent.com/assets/1866463/16362681/d778717e-3bb5-11e6-9a0e-5d3ccf0e65e4.png)

I'll try to come with a solution but wanted to report this here first in case someone wants to help or take it.

**Comment by matthid** [comment]
Seems like this issue has come back :(
