### ISSUE TITLE
Using FsAutoComplete with dotnetcore version of FCS results in compiler errors

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Compiler.Service#600]
#### Repro steps
1. Build FsAutoComplete.Core/Suave with [dotnetcore](https://github.com/7sharp9/FsAutoComplete/tree/dotnetcore)
2. Reference the newly compiled FsAutoComplete.Suave in ionides javascript process invoke rather than the non dotnet core version.
3. Run vs code first choosing an F# file so that the suave service starts up
4. Select a project.json file so that the project cracker is ran
5. Select a source file triggering the error
#### Expected behavior

No errors
#### Actual behavior

```
Bug seen in compiler: System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Compiler-Service-netcore>.$Reshapedmsbuild' threw an exception. ---> System.ArgumentException: An item with the same key has already been added. Key: 4.6
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](TSource[] source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$Reshapedmsbuild..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Compiler.ToolLocationHelper.TargetDotNetFrameworkVersionToSystemVersion(TargetDotNetFrameworkVersion version)
   at Microsoft.FSharp.Compiler.MSBuildResolver.HighestInstalledNetFrameworkVersionMajorMinor()
   at Microsoft.FSharp.Compiler.CompileOps.TcConfig..ctor(TcConfigBuilder data, Boolean validate)
   at Microsoft.FSharp.Compiler.CompileOps.TcConfig.Create(TcConfigBuilder builder, Boolean validate)
   at Microsoft.FSharp.Compiler.IncrementalBuilder.TryCreateBackgroundBuilderForProjectOptions(FrameworkImportsCache frameworkTcImportsCache, FSharpOption`1 scriptClosureOptions, FSharpList`1 sourceFiles, FSharpList`1 commandLineArgs, FSharpList`1 projectReferences, String projectDirectory, Boolean useScriptResolutionRules, Boolean isIncompleteTypeCheckEnvironment, Boolean keepAssemblyContents, Boolean keepAllBackgroundResolutions)

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at Microsoft.FSharp.Compiler.CompileOps.OutputExceptionR@600(StringBuilder os, Exception _arg1)
   at Microsoft.FSharp.Compiler.CompileOps.OutputPhasedError(StringBuilder os, PhasedError err, Boolean flattenErrors)
   at Microsoft.FSharp.Compiler.FSharpErrorInfo.CreateFromException(PhasedError exn, Boolean warn, Boolean trim, range fallbackRange)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$IncrementalBuild.-ctor@976-54.ErrorSinkImpl(PhasedError )
   at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)
   at Microsoft.FSharp.Compiler.IncrementalBuilder.TryCreateBackgroundBuilderForProjectOptions(FrameworkImportsCache frameworkTcImportsCache, FSharpOption`1 scriptClosureOptions, FSharpList`1 sourceFiles, FSharpList`1 commandLineArgs, FSharpList`1 projectReferences, String projectDirectory, Boolean useScriptResolutionRules, Boolean isIncompleteTypeCheckEnvironment, Boolean keepAssemblyContents, Boolean keepAllBackgroundResolutions)
   at Microsoft.FSharp.Compiler.SourceCodeServices.BackgroundCompiler.CreateOneIncrementalBuilder(FSharpProjectOptions options)
   at Microsoft.FSharp.Compiler.SourceCodeServices.BackgroundCompiler.getOrCreateBuilder(FSharpProjectOptions options)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$Service.ParseAndCheckFileInProject@2431.Invoke(CancellationToken _ct)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$Reactor.EnqueueAndAwaitOpAsync@139-2.Invoke(Unit unitVar0)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$Reactor.loop@60-86.Invoke(FSharpOption`1 _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@834-1.Invoke(a a)
   at <StartupCode$FSharp-Core>.$Control.loop@429-54(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@515-1.Invoke(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
#### Known workarounds

None
#### Related information
- Operating system OSX
- Branch: Master
- CoreCLR RTM
- Visual Studio Code

**Comment by matthid** [comment]
I have seen this in my Fake work as well, fix was https://github.com/fsharp/FSharp.Compiler.Service/pull/597/commits/8074762d7613dc3e15120d2d44d440d4f8a829f8#diff-52a3b381c6bc6da5211d19ccdec6484dR2388 (see corresponding PR from don)

**Comment by enricosada** [comment]
OMG, now the dictionary write about the MISSING KEY? that's amazing

```
System.ArgumentException: An item with the same key has already been added. Key: 4.6
```

**Comment by 7sharp9** [comment]
@enricosada Did this work for you?

**Comment by 7sharp9** [comment]
I tried this PR but it didn't help

**Comment by 7sharp9** [comment]
Oh, I think the 1_5 version has to be 1_6 now.  Doh!

**Comment by enricosada** [comment]
Yes, and console app are always `netcoreapp1.0`

**Comment by 7sharp9** [comment]
See: https://github.com/fsharp/FSharp.Compiler.Service/commit/4872c87c65f2be554621e0bf20571037e49e1536#commitcomment-18134562

**Comment by 7sharp9** [comment]
So getting rid of the duplicate key stops the error but now I just get nothing apart from a warning in vscode:

```
[Extension Host] {"Kind":"info","Data":"Parse aborted"}
threadService.ts:207 [Extension Host] rejected promise not handled with 1 second
```

So still dead in the water, no idea on whats wrong.

Bad.

**Comment by 7sharp9** [comment]
So I fiddled with the dependencies and it looks like the project.json -> ProjOptions bit only works with non-wildcard version numbers.

**Comment by 7sharp9** [comment]
old issue, closing
