### ISSUE TITLE
Building package fails because of checksum errors

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsharp/FSharp.Compiler.Service#681]
I cannot build the NuGet package, because "92 source files do not have matching checksums in the Git repository".

#### Repro steps

1. Clone the `FSharp.Compiler.Services` repository
2. Run `build CreatePackage`

#### Expected behavior

The build succeeds, and a NuGet package is created.

#### Actual behavior

The build fails with
```
Running build failed.
Error:
System.Exception: 92 source files do not have matching checksums in the Git repository
   at FSI_0005.SourceLink.SourceLink.Index(IEnumerable`1 sourceFiles, String pdbFile, String gitRepoPath, String url)
   at FSI_0005.Build.clo@110-14.Invoke(String framework)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at FSI_0005.Build.clo@105-13.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
```

#### Known workarounds

None

#### Related information 

* Windows 7
* `master` branch
* .NET 4.6.2

**Comment by rneatherway** [comment]
I've experienced this before when Git was configured to adjust line
endings. I thought this was set in the .gitattributes file now. Which files
and what is your autocrlf set to?

On 12 Dec 2016 2:00 a.m., "TeaDrivenDev" <notifications@github.com> wrote:

I cannot build the NuGet package, because "92 source files do not have
matching checksums in the Git repository".
Repro steps

   1. Clone the FSharp.Compiler.Services repository
   2. Run build CreatePackage

Expected behavior

The build succeeds, and a NuGet package is created.
Actual behavior

The build fails with

Running build failed.
Error:
System.Exception: 92 source files do not have matching checksums in
the Git repository
   at FSI_0005.SourceLink.SourceLink.Index(IEnumerable`1 sourceFiles,
String pdbFile, String gitRepoPath, String url)
   at FSI_0005.Build.clo@110-14.Invoke(String framework)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f,
FSharpList`1 x)
   at FSI_0005.Build.clo@105-13.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in
C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

Known workarounds

None
Related information

   - Windows 7
   - master branch
   - .NET 4.6.2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsharp/FSharp.Compiler.Service/issues/681>, or mute the
thread

**Comment by TeaDrivenDev** [comment]
`autocrlf` is `true`.

These are the files:

```
  git 600bf46da519f42ed6a976c3169d416913229c82, file 45a8a92dbc6bef96bd66ff3f2da88abd6d70e9b8 D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\reshapedreflection.fs
  git e106245e1856c8cbeda1edd0ad776b6242dce328, file 20577f1cbe3bcab6a6476685bd49cf96cd7e9858 D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\sformat.fs
  git 173d7093aff1f976792fd906c0f77b05446828c8, file b07b960408f0c64794eac9661e3aebf6a81da6c4 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\sr.fs
  git eb5e932846fe6a639bc7c46aa73f2ef104a362fa, file 894da589832deb814f6d0c8c1b202b809b21ba65 D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\prim-lexing.fs
  git 3db27bb5031041f080e7253a063b6b61629340df, file cb854dc4cd514df5dbe9b6f6a6d7bbbc05abbada D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\prim-parsing.fs
  git cc392e92c0b4f8ac853a47340504f8450780c8d1, file 5b330e7c0a79520c0dfc7951bd6611f9070bd77a D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\ResizeArray.fs
  git 90197b1d20dc0d0104ba897e2269000e4fdd6f68, file 0b80fe2e279b2146c40a46ff8b3fee50876f9f4b D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\HashMultiMap.fs
  git 1aba0c8e5a2281b585f1a52df551e08234e5f4c8, file 7c11035810a2e2479a47f44d10ffdc2ba9364812 D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\EditDistance.fs
  git 60a2e0bab9b70cd08d63f537138d5cc4c34dd513, file 9d0f73198d5145460c4849522e7be8374f0321bb D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\TaggedCollections.fs
  git 47ccfea4b536e77e4f0e251302e94921b7029d85, file 91d422df7d5fe64e35635a29a4c01db15ecbb767 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\QueueList.fs
  git ae5fd915468fb0ffe80f9e54fd698c7e9809a459, file f8309f7ffa9185f789e4d8bbd715f724d41c6930 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ildiag.fs
  git 5d06388aa2b3f61d2e896e2e81da508454d8cb9d, file 706981eb9ebc31a03737ef4e9ac6116d6a6f0500 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\illib.fs
  git 6d76e518dd50edbdb4d2959ec8fccc60cc3356f8, file f98da5ef482f09559f588a9c981c00720296c212 D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\filename.fs
  git 141f1a0de643451e5ba03202aafbef89d60dbf39, file 637b4ed378d1609400fd034d983959c238a0959b D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\zmap.fs
  git 6d6f9b9b17556185ff971476556a38d41dff2c2a, file 5af7f453548c53219308ba4a78835e67a03ee8ad D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\zset.fs
  git 380d5f4f93f7a262ab04014342bd24cd3802914f, file 996e951290c7264d88edc4ab5f7685e9fd9960f4 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\bytes.fs
  git f9b774095c1e50b1d36b655a912accd9c6897ab2, file 79fd2eb018b743c15e5a608b8ecaca2017344aa0 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\lib.fs
  git 28bb2ff2d6cf84d4327b5ac9662737bd4bd2a462, file 6cd9a7e3be5e8e7f4f1635b35cd78ac4440016c0 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\ErrorResolutionHints.fs
  git 612011cad8ef03f0e27c6e5e5c847af62e14b2dd, file ff2181fa0bfdb5caea62f98339f2cb804725a4e6 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\InternalCollections.fs
  git e17ebb93acaf642e12b0e4276c4c7a94517ab8f3, file 05bca276b30cb46ec320545a8fb8c0f5a55dfca4 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\rational.fs
  git abad7849d9b0289b949d6a69975601a52b24c45d, file 2511afdbc22341a30ded98129ac741e864e4a820 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\range.fs
  git 07b4ae434f8611ec92256b26a402f24c98c99b32, file 685f80a29157e123f2dfcfce60f40d10c6b89ea3 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\ErrorLogger.fs
  git 5c8737e5754cfc99f8582b16bcaf173e026e04a7, file c21cb403b561f2a182e023e1876e9986a93e50c4 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\ReferenceResolver.fs
  git 2655a6c815c3f7734863ff4947ed210e52339829, file 1f8140fcc364150604e21b1d4b8d6c7da0f4b87e D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\il.fs
  git bb8de7ea3ecae9f5d194abd5dabbdd49625f90f3, file f79dccc6af637594826260a0c86a76daff16ca8c D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilx.fs
  git 42f63f21ee0255b9d1692f7ce42e1c06c31af783, file e8d4ddd25d65c196a73a74d352509bbf285fa323 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilascii.fs
  git f6bc4d1e553e207160a940e7ec158693870a025c, file 5ab77b61c666cd66889a7d1db63a6d21bd18dc49 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilmorph.fs
  git a373e769c4c195415eed256f10b18cf2fd420df8, file fc4df765c3ce0cb7b7a93d6674a2e7e49317561b D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilsupp.fs
  git 157a28f18077f577f5fe28be50084dae96a7f86b, file 42cb620be344dba0262d27d0136bcc1b850a2052 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilbinary.fs
  git fbb76f24ef7f0653de880f5fd79bdc1393d3b671, file 61bf157102399150e1c24a47d8c9116c8cb968bd D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilread.fs
  git 64fef2369d0e1cc458d6977bd85cc6868ec7a380, file e0526d7820a1484381344dfa56cfb7e4ccdd8039 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilwritepdb.fs
  git 62196b77a39c10a531897a447fc918476d255559, file e3e33a3f98e41f405a5839e2848f21e5544226cb D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilwrite.fs
  git 5bcb5d621ead88e52fece7f70abd84d93f53ab6e, file bcb67bd20bf84db32033e335f00a786437d09d89 D:\Development\OpenSource\FSharp.Compiler.Service\src\absil\ilreflect.fs
  git 020a767b8f68cd78674e398469ed96df284ce114, file 1b7f5b2af4064b8f00e2577c7426cc738b46310e D:\Development\OpenSource\FSharp.Compiler.Service\src\utils\CompilerLocationUtils.fs
  git 542918cc96bb7a6f554be7170ca556755e3f0a31, file 118d03ecf2db434c8b28fea44339c78ccebd125b D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\PrettyNaming.fs
  git bc4cccbe4c2daa4676c462959af98a48614e8e2b, file 19247d29a260a41536a0438601b2c53919bbf8d5 D:\Development\OpenSource\FSharp.Compiler.Service\src\ilx\ilxsettings.fs
  git d3c47ea5a9c4d41e9277380bd02557559a0645b2, file be2142eb6460b7f4ecdcd8e0d5b390804ceaf5db D:\Development\OpenSource\FSharp.Compiler.Service\src\ilx\EraseClosures.fs
  git 4bf5535e4411b6a144554f512185fc90c5a06a0c, file fb76c713dba6f3fd064546b5e06b752b99aad336 D:\Development\OpenSource\FSharp.Compiler.Service\src\ilx\EraseUnions.fs
  git 08a4c152e13e81ffbc74260f75938c3d236130dd, file 1afe392f6d035dcea3cca7a38fdf359592d9b928 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\UnicodeLexing.fs
  git 187211fb77c6c150307727cf2581daebd290d8d4, file 7f0a42d0dbc125607ff4c7fc0c09310372a5fe02 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\layout.fs
  git 360f14c73cd2b828820158f983fd6a6355984a8e, file 2d6f79ed6f4153f95596200c2df83858a6881427 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\ast.fs
  git f441549997d97c44147ba57a2acc8d951f785165, file 3c4a444ec0deea46627350afe759ce373024308d D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\lexhelp.fs
  git 19f84669aaa5beea5c24032e3af1b4b9dc286c31, file 4a9940bfdebdf3b5260d1995bdbf5e70764357b2 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\LexFilter.fs
  git 3bde45d11715934a544a11ce6ebf0474dcdf9ea5, file d2bdf7e4f80fad04c97462a69f84edbe65a23aa9 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\tainted.fs
  git 27efa073863dafe4df6c08c44ec0acc9f5bc0df4, file 5833b9ca30d1f33f4b9403cab6c868873e2c0c84 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\ExtensionTyping.fs
  git dfd981c2daff4b8c8910d8a0d9e4e01aa2b46642, file 46c84e62fbd28efe0db4e4c7a1297d0cf930581b D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\QuotationPickler.fs
  git c9d5584572759376a0bf7f577c7cf1da6e336952, file 26950333eb9565364eb7aece298ecf49c3550eca D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\tast.fs
  git 1a5b753a2801735a83ab110882465704f4b0500c, file a51df89b45ae4e292cb9049404f94789b9b6b4de D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\TcGlobals.fs
  git 773eeebb1a66b1b99cd134e087cbe8fc0276a54d, file 9a182fd3b93e17a9ba35bde8b57749796552fe01 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\TastOps.fs
  git 0392ea8c292f9b94381db89e948df34867f4ab91, file 74d9073fde69ba8a238df081548c6980d3cc6f67 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\TastPickle.fs
  git c0bca3ec1e08b8604a95ccf9ed9912f91250718c, file b6bee4906fa67a1e2a122b6d5c6292db97d868c3 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\import.fs
  git f2070133a8b3c2caf834edeb2d13292b235f58a9, file 4177fe8796a72318433955b513a2ca21e8fc7c5b D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\infos.fs
  git 525995cca1f393d25f5263ae23971bae7fd31588, file 8afc410c1c0f790883b34c76c72528accc3f4a6f D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\AccessibilityLogic.fs
  git 82c36d3f8fa912102b568da74ddb9962240e0157, file 01d9145564a0c697e57f850bbc68ab0c0667b21e D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\AttributeChecking.fs
  git f0697622b67aef4ba190d246df46d01e8c317d04, file 457f6a12e64a1875f1a435d45ceabb86b8ca6dc3 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\InfoReader.fs
  git 1844cc6437fc224d22eecbfe97c0b083d4560e5a, file 8e45adce6ee89025f809248683d380051c21dac5 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\NicePrint.fs
  git 088f761ac707b846a244f597e3e81fdbd28627f7, file ebce289ceff04f7eab835f1348c4ab1a64a7f93f D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\AugmentWithHashCompare.fs
  git cd3b290e8c996b91bb715645097acecd1292a21b, file 1c2fe6bfd5f781ff2aa878fc33e339932d60091c D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\NameResolution.fs
  git c3cdc8d338244bbb54b992f4e5b0176fb1950dd5, file 803d575cfb2bff14eaed54219269dbbc8a577248 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\TypeRelations.fs
  git 55a573d1e9a76c48198c134046f47e383f30114b, file 84f14479b8f92a32a383c1d27804b3e755a88203 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\SignatureConformance.fs
  git b446ea5c06da2adb1779685a32ac265febd14c86, file 1dcc195ec525e387a0170aafc2f307f2f30e27e5 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\MethodOverrides.fs
  git 794507bd9345abfaa2522f4af1ce14f35b3158da, file 883c3bcc8c3edf85c33ffc06faa8154e68fcf39b D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\MethodCalls.fs
  git 2a85ccce9bc5c6699e67cfcf1450473c769385b7, file f5e70e4de4790b27628ac44d3ce9e3bcdb04aa6a D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\PatternMatchCompilation.fs
  git f51bb3a85386f588ded0edc87c52fa173a0978f6, file e85049aa9c7bcf82be4b8f03f89f402170f21791 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\ConstraintSolver.fs
  git 06f43d2aa92b18b800561bac7b82a90f8c36887e, file 45a3309f274e17d2d49984e3301ca5a4fb40d1b4 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\CheckFormatStrings.fs
  git dd74bfd8bd80fa738f2779989c32fbade194e936, file 7644c27348ddedc71121d030a77d313294a467fe D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\FindUnsolved.fs
  git 2c4875502d50315109c9e9bd6a888f5bfece6305, file a41798011848ccae4c690ffda7f6a084f72e5e55 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\QuotationTranslator.fs
  git 9926771ffce8a290e0e2af196f00a491cd56dd5c, file 4bcd6d92594724f6ec5c1c841fe76b8eb92bda96 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\PostInferenceChecks.fs
  git 44e4a6d74f72fb561858a1eb6bb0ea188a55f85c, file 2071d0397f7aadcdd7137156a7089d2e1390cf56 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\TypeChecker.fs
  git 242d3bfde236edae0396eeecfa6f7995fb45e52c, file 783c0d302b708b08d935dc80c450e1e64f3b363f D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\Optimizer.fs
  git beb3a8e25f483df2c349c2fad0abfc8850ba79bc, file 9b09205751db8cd25e5b6f8f856a367cde9e8e83 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\DetupleArgs.fs
  git b8b1d0d4717358b10cfe9a2a77f81bc73faebf5d, file 9f1cb73cfd4726173fc2a5f1e0fd6d033fcfa861 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\InnerLambdasToTopLevelFuncs.fs
  git 5ee20ea0f2483cbbc0f94513ef8cf251fb106cc4, file 661157fef2d285e90fde356f40adbd424bd5d3e4 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\LowerCallsAndSeqs.fs
  git b32e07f0798046eeb429186d156d722bb28e56a4, file 8513344cdb9353e892e8eb4677a6bb045169722f D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\autobox.fs
  git 7192b9777fa3b5bf590fa0e2df7687c8c5d3d38c, file 455697e44c78a94902cd111a37e7776af03b70a1 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\IlxGen.fs
  git ad8260546b1561b9d75ced0c132af6ff09a8a768, file 7363ac9fecb55d7fc5c65911d49bc11d38ba4389 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\CompileOps.fs
  git f74f5fa427837ffe19ced9c623ad9d5b1d64b960, file 8720d6554877152d210f7ff08e38ebcc8672ce73 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\CompileOptions.fs
  git 8d05baaa0221e459bc94acd6ed3fb234ba7de5f6, file b87e8f72c9176827c07b93462a262b1cbc329a0d D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\fsc.fs
  git 4ecac12c365a10f1e8ce7a955ca2c8066d334c95, file 87e290a6d93ff157c5d6dfde0abc5986ed09b9e4 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\IncrementalBuild.fs
  git 6c5c27d2a9e5b829f4c7dddc675e0f78e26c764d, file 03e7203b3a7c58dea24564096e14a01dd2902aeb D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\Reactor.fs
  git c4b9c34811caea00e1263aaf05c3434afcf8bb7b, file edff90fecfc60e9e7d4060809215882220a6a7e2 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\ServiceDeclarations.fs
  git 936661276079e5014dae41d877cd1da0dd7643ab, file 3cefdead41af711a4a89bfba8a51fe6eaf87e3be D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\Symbols.fs
  git f78e3a1f12e9fa652292770cdeae2e9182284b1b, file 3ab1ae562497c21fcbd28a4476ec83f22c57f25c D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\Exprs.fs
  git 53f0d65ed0140c7692a9b85996c3ebd4e82e376b, file 37b1dfedfaec088e004ece6a2ee0cabdc1453199 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\ServiceLexing.fs
  git bfbb50f9542d535b3f80c7295337b878c4d0e55b, file 2070761ffd4976a233403d2b37ae3401c7883cad D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\ServiceParseTreeWalk.fs
  git e06dd8cbc7cea33635ce9a4f72f2075c82319cdc, file c908a6a65d6212ba46b8cf9f31230b3475d1e559 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\ServiceNavigation.fs
  git 1290772da3ce48930002cccec0a592e2f48a16db, file d1b0e51c8e52ea525e09c4ca6211d7d6ab2b8e74 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\ServiceParamInfoLocations.fs
  git edb25eaf59243361b6e53f3b888a954b08d35b38, file 5feb031eef542ab9078f8b7422646a2cff439c4e D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\ServiceUntypedParse.fs
  git 3fbcf906f4a3c4ddde4722adef01369edc61fa7b, file f85b1f745aa59c7f2251521bf3a9b141f6cb6969 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\SimulatedMSBuildReferenceResolver.fs
  git 50bfa1fa5730bbd36b473e9988f0ac85f93138f5, file 85a058cf24debc8d8d7c30f978dd77e4e74eb050 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\service.fs
  git e9a596e3277b7d294d42f4162fd93f91a158683c, file 1a7cb5ad782fea23eb01c8c9679394086e2aff1e D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\vs\SimpleServices.fs
  git ddeae1ff2f185070a089fac9a845a29c32895c17, file 225958cf405c58f5f3ee9bd711585b34638c5401 D:\Development\OpenSource\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs
```

**Comment by dsyme** [comment]
I think you need to use

    git config --global core.autocrlf input
