### ISSUE TITLE
Two test failures when VS2017 installed

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Compiler.Service#718]
Two test failures on Windows when VS2017 RC installed

#### Repro steps

    .\build All.NetFx

#### Expected behavior

Tests pass

#### Actual behavior

Tests fail

#### Related information 
```
Tests run: 213, Errors: 2, Failures: 0, Inconclusive: 0, Time: 87.8881411043107 seconds
  Not run: 4, Invalid: 0, Ignored: 4, Skipped: 0

Errors and Failures:
1) Test Error : FSharp.Compiler.Service.Tests.ExprTests.Check use of type provider that provides calls to F# code
   System.Runtime.Serialization.SerializationException : Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFileLogged(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp, FSharpOption`1 enableLogging) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\FSharp.Compiler.Service.ProjectCracker\ProjectCracker.fs:line 75
   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFile(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\FSharp.Compiler.Service.ProjectCracker\ProjectCracker.fs:line 82
   at FSharp.Compiler.Service.Tests.ExprTests.Check use of type provider that provides calls to F# code() in C:\GitHub\dsyme\FSharp.Compiler.Service\tests\service\ExprTests.fs:line 868

2) Test Error : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing example 1 Release Configuration
   System.Runtime.Serialization.SerializationException : Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFileLogged(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp, FSharpOption`1 enableLogging) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\FSharp.Compiler.Service.ProjectCracker\ProjectCracker.fs:line 75
   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFile(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\FSharp.Compiler.Service.ProjectCracker\ProjectCracker.fs:line 82
   at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing example 1 Release Configuration() in C:\GitHub\dsyme\FSharp.Compiler.Service\tests\service\ProjectOptionsTests.fs:line 66


Tests Not Run:
1) Ignored : FSharp.Compiler.Service.Tests.FsiTests.EvalExpression function value 4
   Failing test for #135
2) Ignored : Tests.Service.Editor.Find function from member 1
   Currently failing, see #139
3) Ignored : Tests.Service.Editor.Symbol based find function from member 1
   Currently failing, see #139
4) Ignored : Tests.Service.ProjectAnalysisTests.Test project1 should not throw exceptions on entities from referenced assemblies
   FCS should not throw exceptions on FSharpEntity.BaseType
```

**Comment by dsyme** [comment]
Same root cause as https://github.com/fsharp/FSharp.Compiler.Service/pull/719, closing as duplicate
