### ISSUE TITLE
[Debug] Assert thrown when using fsc.exe with FCS

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FSharp.Compiler.Service#759]
```
Exception thrown: 'System.Exception' in FSharp.Core.dll
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Failed to compute key in OpenILModuleReaderAfterReadingAllBytes cache. Falling back to uncached.
---- Assert Long Message ----

   at Microsoft.FSharp.Compiler.AbstractIL.ILBinaryReader.OpenILModuleReaderAfterReadingAllBytes(String infile, ILReaderOptions opts) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\absil\ilread.fs:line 3983
   at Microsoft.FSharp.Compiler.CompileOps.OpenILBinary[a](String filename, Boolean optimizeForMemory, Boolean openBinariesInMemory, FSharpOption`1 ilGlobalsOpt, FSharpOption`1 pdbPathOption, a shadowCopyReferences) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\CompileOps.fs:line 2478
   at Microsoft.FSharp.Compiler.CompileOps.TcConfig..ctor(TcConfigBuilder data, Boolean validate) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\CompileOps.fs:line 2623
   at Microsoft.FSharp.Compiler.CompileOps.TcConfig.Create(TcConfigBuilder builder, Boolean validate) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\CompileOps.fs:line 2829
   at Microsoft.FSharp.Compiler.Driver.AdjustForScriptCompile(CompilationThreadToken ctok, TcConfigBuilder tcConfigB, FSharpList`1 commandLineSourceFiles, LexResourceManager lexResourceManager) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\fsc.fs:line 207
   at Microsoft.FSharp.Compiler.Driver.main0[a](a ctok, String[] argv, Resolver referenceResolver, Boolean bannerAlreadyPrinted, Boolean openBinariesInMemory, Exiter exiter, ErrorLoggerProvider errorLoggerProvider, DisposablesTracker disposables) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\fsc.fs:line 1701
   at Microsoft.FSharp.Compiler.Driver.typecheckAndCompile(CompilationThreadToken ctok, String[] argv, Resolver referenceResolver, Boolean bannerAlreadyPrinted, Boolean openBinariesInMemory, Exiter exiter, ErrorLoggerProvider loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\fsc.fs:line 2080
   at Microsoft.FSharp.Compiler.Driver.mainCompile(CompilationThreadToken ctok, String[] argv, Resolver referenceResolver, Boolean bannerAlreadyPrinted, Boolean openBinariesInMemory, Exiter exiter, ErrorLoggerProvider loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\fsc.fs:line 2097
   at Microsoft.FSharp.Compiler.SourceCodeServices.CompileHelpers.result@2369-7.Invoke(Exiter exiter) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\vs\service.fs:line 2370
   at Microsoft.FSharp.Compiler.SourceCodeServices.CompileHelpers.tryCompile(ErrorLogger errorLogger, FSharpFunc`2 f) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\vs\service.fs:line 2358
   at Microsoft.FSharp.Compiler.SourceCodeServices.CompileHelpers.compileFromArgs(CompilationThreadToken ctok, String[] argv, Resolver referenceResolver, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\vs\service.fs:line 2368
   at <StartupCode$FSharp-Compiler-Service>.$Service.Compile@3120-1.Invoke(Unit unitVar) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\vs\service.fs:line 3120
   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.delay@766.Invoke(CancellationToken ct) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\absil\illib.fs:line 766
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@146-2.Invoke(CompilationThreadToken ctok) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\vs\Reactor.fs:line 149
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.loop@67-91.Invoke(FSharpOption`1 _arg2) in C:\Users\lr\Source\Repos\FSharp.Compiler.Service\src\fsharp\vs\Reactor.fs:line 77
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
   at <StartupCode$FSharp-Core>.$Control.loop@430-54(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@516-1.Invoke(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

__Branch:__ master

![image](https://cloud.githubusercontent.com/assets/4236651/25310031/596792c0-27db-11e7-9ded-0e993463e71f.png)

I was using fsc with a response file:
[fscrf.txt](https://github.com/fsharp/FSharp.Compiler.Service/files/949422/fscrf.txt)

The same response file does NOT assert with visualfsharp fsc.

**Comment by 0x53A** [comment]
Also, can we replace all asserts with fail-fast?  Afaik the CI is release only, so they are relatively useless...

**Comment by dsyme** [comment]
Does this repro consistently? What was the exception thrown?

**Comment by Krzysztof-Cieslak** [comment]
I'm pretty sure I've hit same assertions when I was last time working on FCS. 

I've always assumed that's expected behavior ;-)

**Comment by 0x53A** [comment]
To reproduce, switch the configuration to debug and start the project __UntypedTree__.

**Comment by dsyme** [comment]
Spring cleaning in preparation for unifying this repo with visualfsharp: Closing as this is fixed in visualfsahrp master.  It will eventually be released
