### ISSUE TITLE
StopProcessingExn since 34.0.1

### ISSUE THREAD

**Issue by goswinr** [fsharp/FSharp.Compiler.Service#935]
Since version 34.0.1 ( and in the current 35.0.0 too) I get an Exception  when creating a FSI Evaluation Session while hosting my scripting editor (with FCS) in another CAD app.

As standalone app it still works fine.

I am looking for help to debug this.
Is there a way to see how the FSI session constructor code changed between 33.0.1 and 34.0.1 ?

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Error creating evaluation session(TcImports.BuildNonFrameworkTcImports): StopProcessingExn None
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver)
   at Seff.Fsi.startSession()
```

**Comment by goswinr** [comment]
maybe related: https://github.com/fsharp/FSharp.Compiler.Service/issues/879

**Comment by goswinr** [comment]
this error is preceded by 
`error FS0084: Assembly reference 'FSharp.Core.dll' was not found or is invalid` 
even though FSharp.Core.dll (4.7.1) is there (in the same folder).

**Comment by dsyme** [comment]
Hmmmm

I think it might be best to open this in http://github.com/dotnet/fsharp with a repro script.  There must have been a change there

**Comment by goswinr** [comment]
closing because tracked in https://github.com/dotnet/fsharp/issues/9064
